# Generated by Django 4.2.5 on 2023-11-25 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itmclass', models.CharField(max_length=50, null=True)),
                ('classname', models.CharField(max_length=50, null=True)),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('cusstomer_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user_datecreated', models.DateTimeField(auto_now_add=True)),
                ('user_dateupdated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itmname', models.CharField(max_length=100, null=True)),
                ('itmtitle', models.CharField(max_length=20, null=True)),
                ('itmdesc', models.CharField(max_length=200, null=True)),
                ('itm_old_price', models.IntegerField(null=True)),
                ('itm_new_price', models.IntegerField(null=True)),
                ('itm_isactive', models.BooleanField(default=True)),
                ('sku_no', models.CharField(blank=True, max_length=10, null=True)),
                ('itm_tags', models.CharField(blank=True, max_length=10, null=True)),
                ('itm_barcode', models.CharField(blank=True, max_length=10, null=True)),
                ('itm_datecreated', models.DateTimeField(auto_now_add=True)),
                ('itm_dateupdated', models.DateTimeField(auto_now=True)),
                ('itmclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itmsubclass', models.CharField(max_length=50, null=True)),
                ('classname', models.CharField(max_length=50, null=True)),
                ('isactive', models.BooleanField(default=True)),
                ('itmclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('review', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.products')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='itmsubclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.subcategory'),
        ),
        migrations.AddField(
            model_name='products',
            name='vendoraddedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer'),
        ),
        migrations.CreateModel(
            name='product_variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varient_name', models.CharField(blank=True, max_length=10, null=True)),
                ('color_code', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.products')),
            ],
        ),
        migrations.CreateModel(
            name='product_metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_link', models.CharField(blank=True, max_length=50, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=50, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.products')),
            ],
        ),
        migrations.CreateModel(
            name='product_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/uploads/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/uploads/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/uploads/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/uploads/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images/uploads/')),
                ('product_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.products')),
            ],
        ),
        migrations.CreateModel(
            name='orders_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('shippeddate', models.DateTimeField(null=True)),
                ('deliverydate', models.DateTimeField(null=True)),
                ('paymentid', models.CharField(max_length=50)),
                ('order_dateupdated', models.DateTimeField(auto_now=True)),
                ('itemno', models.ManyToManyField(to='store.products')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('abline1', models.CharField(max_length=200, null=True)),
                ('abline2', models.CharField(max_length=200, null=True)),
                ('abline3', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('zip', models.IntegerField()),
                ('isactive', models.BooleanField(default=False)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
