# Generated by Django 4.2.5 on 2023-11-25 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
    ]
