# Generated by Django 4.2.5 on 2023-11-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_products_itmtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='itmdesc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
