# Generated by Django 4.2.5 on 2023-11-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_products_itmdesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(max_length=50)),
                ('offer_desc', models.CharField(max_length=100)),
                ('offer_image', models.ImageField(upload_to='images/uploads/')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
