# Generated by Django 4.2.5 on 2024-02-15 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0005_alter_store_details_store_images_and_more'),
        ('store', '0008_home_offers'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('shippeddate', models.DateTimeField(null=True)),
                ('deliverydate', models.DateTimeField(null=True)),
                ('paymentid', models.CharField(max_length=50)),
                ('order_dateupdated', models.DateTimeField(auto_now=True)),
                ('cutomer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
                ('itemno', models.ManyToManyField(to='store.products')),
                ('vendor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.store_details')),
            ],
        ),
        migrations.DeleteModel(
            name='orders_customer',
        ),
    ]
