# Generated by Django 4.2.5 on 2024-02-15 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='if_on_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.products'),
        ),
        migrations.CreateModel(
            name='discount_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('offer_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.discount')),
            ],
        ),
    ]
