# Generated by Django 4.2.5 on 2024-02-15 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_discount_if_on_product_discount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount_type',
            name='offer_type',
        ),
        migrations.AlterField(
            model_name='discount',
            name='offer_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.discount_type'),
        ),
    ]
