# Generated by Django 4.2.5 on 2024-02-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_discount_type_offer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='if_on_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category'),
        ),
    ]
