# Generated by Django 4.2.5 on 2024-02-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_discount_is_created_alter_discount_if_on_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
