# Generated by Django 4.2.5 on 2024-02-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_discount_vendor_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='is_created',
            new_name='is_active',
        ),
    ]
