# Generated by Django 4.2.5 on 2024-02-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_discount_if_on_product_order_invoices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_invoices',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='order_invoices',
            name='vendor_id',
        ),
    ]
