# Generated by Django 4.2.5 on 2024-02-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_customer_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
