# Generated by Django 4.2.5 on 2024-02-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_address_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cusstomer_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/uploads/'),
        ),
    ]
