# Generated by Django 4.2.5 on 2024-02-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_customer_cusstomer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_invoices',
            name='invoice_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
