# Generated by Django 4.2.5 on 2024-02-23 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_lastlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shipto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.address'),
        ),
    ]
