# Generated by Django 4.2.5 on 2024-02-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_rename_itemno_orders_items_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
