# Generated by Django 4.2.5 on 2024-02-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_remove_customer_referred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_isverified',
            field=models.BooleanField(default=False),
        ),
    ]
