# Generated by Django 4.2.5 on 2024-02-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_customer_email_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastlogin',
            name='browser_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lastlogin',
            name='device_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
