# Generated by Django 4.2.5 on 2024-03-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_customer_email_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vendor_active_email',
            field=models.BooleanField(default=False),
        ),
    ]
