# Generated by Django 4.2.5 on 2024-03-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_customer_vendor_active_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastlogin',
            name='browser_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lastlogin',
            name='device_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
